FROM eclipse-temurin:21-jre
WORKDIR /work
RUN useradd -u 1001 quarkus && chown -R 1001 /work
USER 1001
COPY target/quarkus-app/lib/ /work/lib/
COPY target/quarkus-app/*.jar /work/
COPY target/quarkus-app/app/ /work/app/
COPY target/quarkus-app/quarkus/ /work/quarkus/
EXPOSE 8080
ENTRYPOINT ["java","-Dquarkus.http.host=0.0.0.0","-jar","/work/quarkus-run.jar"]